# Generated by Django 6.0.3 on 2026-03-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
