# Generated by Django 6.0.3 on 2026-03-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_genre_id_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='executor',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
